version: '3'
services:
  redis:
    image: nodejs:latest
    expose:
      - 6379
  app:
    build: .
    volumes:
      - .:/usr/src/app/
      - dependencies:/usr/src/app/node_modules
    working_dir: /usr/src/app
    depends_on:
      - redis
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    command: npm run dev
volumes:
  dependencies: